PeopleList feature added
dominikblak/movies-browser pull request #20
Opened 2021-12-06 14:00 UTC by Przemek-Przybylak

Hejka dodałem listę aktorów.
Jedyny problem to  brakująca 4 aktorów ( strona w API ma 20 a nam potrzebnych jest 24 )

2021-12-06 15:11 UTC, dominikblak approved these changes
Kawał świetnej roboty Przemek :-)

2021-12-06 15:31 UTC, dominikblak commented on src/common/Pagination/index.js
> +  const allPages = hashString === "#/movies" ? moviesPages : peoplePages;
Tu pojawia się błąd przy kliknięciu w Button "Last" w  paginacji w sekcji people  - ustawiany jest "undefined" zamiast "total_results" z API.

2021-12-06 15:35 UTC, dominikblak requested changes
Kawał dobrej roboty ;-) brakuje tylko przekazania "total_results" z API do paginacji - wywala błąd na stronie 500.

2021-12-07 07:36 UTC, piotrekbrzegowy approved these changes
Dobra robota! :)

2021-12-07 07:38 UTC, piotrekbrzegowy commented on src/features/PeopleList/PeopleTile/index.js
> -            <Image src={poster_path ? `https://image.tmdb.org/t/p/w500${poster_path}` : "no image"} alt={`${title} poster`} />
Tutaj dodałbym tekst alternatywny zdjęcia również, może imię i nazwisko osoby z api?

2021-12-07 16:02 UTC, dominikblak reviewed
Hej Przemku ;-) Super robota - paginacja na people już działa. Jeszcze tylko trzeba analogiczną poprawkę trzeba zrobić na movieList (ten sam błąd) i można mergować :-)

2021-12-07 18:24 UTC, merged